SELECTED_FACTOR_SPECS = [
    {
        "factor": "log_market_cap",
        "theme": "information_liquidity_size",
        "weight": 0.10,
        "direction": 1.0,
        "rationale": "Exhaustive IC에서 높은 평균 IC를 보인 규모/유동성 proxy입니다.",
    },
    {
        "factor": "rating_total_count",
        "theme": "information_liquidity_size",
        "weight": 0.10,
        "direction": 1.0,
        "rationale": "투자의견 coverage가 넓은 종목이 더 안정적인 forward return IC를 보였습니다.",
    },
    {
        "factor": "target_total_count",
        "theme": "information_liquidity_size",
        "weight": 0.10,
        "direction": 1.0,
        "rationale": "목표주가 coverage가 넓은 종목의 다음 월 수익률 순위 상관이 양호했습니다.",
    },
    {
        "factor": "target_confidence",
        "theme": "information_liquidity_size",
        "weight": 0.10,
        "direction": 1.0,
        "rationale": "목표주가 consensus 신뢰도 proxy로 IC와 top-bottom 성과가 모두 양호했습니다.",
    },
    {
        "factor": "analyst_coverage",
        "theme": "information_liquidity_size",
        "weight": 0.08,
        "direction": 1.0,
        "rationale": "컨센서스가 비어 있는 종목을 평균 매력도로 오해하지 않기 위한 coverage 축입니다.",
    },
    {
        "factor": "sales_fy1",
        "theme": "forward_consensus",
        "weight": 0.09,
        "direction": 1.0,
        "rationale": "FY1 매출 컨센서스 레벨이 exhaustive IC 상위권이었습니다.",
    },
    {
        "factor": "sales_fy2",
        "theme": "forward_consensus",
        "weight": 0.07,
        "direction": 1.0,
        "rationale": "FY2 매출 컨센서스도 양의 IC를 보여 forward 성장 축으로 사용했습니다.",
    },
    {
        "factor": "sales_spread_fy1_minus_fy0",
        "theme": "forward_consensus",
        "weight": 0.07,
        "direction": 1.0,
        "rationale": "FY1-FY0 매출 증가폭이 양호한 IC를 보였습니다.",
    },
    {
        "factor": "sales_spread_fy2_minus_fy1",
        "theme": "forward_consensus",
        "weight": 0.06,
        "direction": 1.0,
        "rationale": "FY2-FY1 매출 증가폭으로 중기 성장 방향을 반영했습니다.",
    },
    {
        "factor": "op_spread_fy1_minus_fy0",
        "theme": "quality_growth",
        "weight": 0.07,
        "direction": 1.0,
        "rationale": "영업이익 증가폭은 매출 성장보다 작은 비중으로 품질 축에 넣었습니다.",
    },
    {
        "factor": "eps_growth_fy2_vs_fy0",
        "theme": "forward_eps",
        "weight": 0.04,
        "direction": 1.0,
        "rationale": "forward EPS 계열은 full-sample IC는 양호하지만 walk-forward OOS가 약해 보조 신호로 낮은 비중만 사용했습니다.",
    },
    {
        "factor": "eps_yield_growth_fy2_vs_fy0",
        "theme": "forward_eps",
        "weight": 0.04,
        "direction": 1.0,
        "rationale": "EPS 성장률을 가격 대비 수익성 관점으로 보완하되, OOS 결과를 감안해 보조 신호로 제한했습니다.",
    },
    {
        "factor": "earnings_yield_per",
        "theme": "valuation",
        "weight": 0.02,
        "direction": 1.0,
        "rationale": "PER cheapness를 높을수록 좋은 점수로 바꾼 보조 valuation 신호입니다. walk-forward 선택 빈도가 약해 낮은 비중으로만 사용합니다.",
    },
    {
        "factor": "book_to_price_pbr",
        "theme": "valuation",
        "weight": 0.02,
        "direction": 1.0,
        "rationale": "PBR cheapness를 높을수록 좋은 점수로 바꾼 보조 valuation 신호입니다. 과열 종목 과대비중 방지 용도입니다.",
    },
    {
        "factor": "sales_to_price_psr",
        "theme": "valuation",
        "weight": 0.02,
        "direction": 1.0,
        "rationale": "PSR cheapness를 높을수록 좋은 점수로 바꾼 보조 valuation 신호입니다. 메인 알파가 아니라 낮은 강도의 보완 신호입니다.",
    },
]


SELECTED_BL_VIEW_SPECS = [
    ("composite", 0.070, 0.35),
    ("information_liquidity_size", 0.040, 0.30),
    ("forward_consensus", 0.050, 0.30),
    ("quality_growth", 0.040, 0.25),
    ("forward_eps", 0.050, 0.30),
    ("valuation", 0.020, 0.10),
]
